server:
  port: 8888
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml

logging:
  level:
    root:
      info


spring:
  cache:
    type: redis
    redis:
       host: 127.0.0.1 # server host
       port: 6379 # connection port
       database: 0
       password:
       lettuce:
          pool:
            min-idle: 0
            max-idle: 8
            max-wait: -1ms
            max-active: 8
          shutdown-timeout: 100ms
  datasource:
#      druid:
#        url:  jdbc:mysql://172.16.9.4:3306/bim360
#        username: root
#        password: root
    primary:
      driver-class-name: com.mysql.jdbc.Driver
      url:  jdbc:mysql://172.16.9.4:3306/bim360
      username: root
      password: root
    secondary:
      driver-class-name: com.mysql.jdbc.Driver
      url:  jdbc:mysql://172.16.9.4:3306/bim360
      username: root
      password: root
    profiles:
        active: dev

#spring:
#  datasource:
#    druid:
#      url:  jdbc:mysql://172.16.9.4:3306/bim360?useUnicode=true&characterEncoding=utf-8&noAccessToProcedureBodies=true
#      username: root
#      password: root
#  ds_center:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name:  com.mysql.jdbc.Driver
#    url:  jdbc:mysql://172.16.9.4:3306/bim360?useUnicode=true&characterEncoding=utf-8&noAccessToProcedureBodies=true
#    username: root
#   password: root
#  ds_manage:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name:  com.mysql.jdbc.Driver
#    url:  jdbc:mysql://172.16.9.4:3306/ccbimcloud?useUnicode=true&characterEncoding=utf-8&noAccessToProcedureBodies=true
#    username: root
#    password: root
